/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dezzy_neuronz2_math_cl_memory_MemoryManager */

#ifndef _Included_dezzy_neuronz2_math_cl_memory_MemoryManager
#define _Included_dezzy_neuronz2_math_cl_memory_MemoryManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dezzy_neuronz2_math_cl_memory_MemoryManager
 * Method:    alignedMalloc
 * Signature: (JJ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_dezzy_neuronz2_math_cl_memory_MemoryManager_alignedMalloc
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     dezzy_neuronz2_math_cl_memory_MemoryManager
 * Method:    alignedFree
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_dezzy_neuronz2_math_cl_memory_MemoryManager_alignedFree
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
